apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: apex-meridian-api
    newName: apex-meridian-api
    newTag: local
  - name: apex-meridian-frontend
    newName: apex-meridian-frontend
    newTag: local

